### ISSUE TITLE
Links in Tutorial PDF not working

### ISSUE THREAD

**Issue by baatch** [Azure-Samples/cdm-azure-data-services-integration#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
Links in Tutorial PDF not working

### Minimal steps to reproduce
>
Links in Tutorial PDF not working

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by billgib** [comment]
While we get this fixed, please use the tutorial in the readme which is in markdown and has working links

**Comment by billgib** [comment]
We've decided that we will not include a PDF file version of the tutorial, but instead just deliver a markdown version, consistent with the way Microsoft delivers other online documentation.
