### ISSUE TITLE
Azure Explorer and access management

### ISSUE THREAD

**Issue by rajmsft** [Azure-Samples/cdm-azure-data-services-integration#7]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>While creating permission for Power BI services, storage explorer is not able to recognize the object Ids.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by theresapalmer** [comment]
@rajmsft - could you try updating to the latest Storage Explorer? There was a release on 12/18 that fixed a bug relating to setting permissions for service principle OIDs. Please reopen if you're still having an issue!
